services:
  app:
    container_name: nexus-processor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - TZ=America/Sao_Paulo
      - NODE_ENV=production
      - PORT=3000
      - RABBITMQ_URL=amqp://nexus:nexus-challenge@rabbitmq:5672
      - MONGO_URL=mongodb://root:nexus-challenge@mongo:27017/orders?authSource=admin
      - RETRY_MAX_ATTEMPTS=3
      - RETRY_INITIAL_DELAY_MS=1000
      - RETRY_BACKOFF_FACTOR=2
      - BATCH_SIZE=10
      - BATCH_TIMEOUT_MS=5000
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: nexus
      RABBITMQ_DEFAULT_PASS: nexus-challenge
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: on-failure

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    restart: unless-stopped

  mongo:
    container_name: mongo-db
    image: mongo:5.0
    ports:
      - '27017:27017'
    environment:
      - TZ=America/Sao_Paulo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=nexus-challenge
      - MONGO_INITDB_DATABASE=orders
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: >
        mongosh --quiet -u root -p nexus-challenge --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure
    command: mongod --auth

volumes:
  mongo-data:
    driver: local
  rabbitmq-data:
    driver: local
  redis-data:
    driver: local
